-- สคริปต์แปลง Part/Model เป็นโค้ดสร้างวัตถุ (อย่างง่าย)
local TargetFolder = workspace -- หรือระบุเฉพาะโมเดล เช่น workspace.Building

local function serializePart(part)
    if not part:IsA("BasePart") then return "" end
    
    local code = string.format(
        [[
local p = Instance.new("%s")
p.Name = "%s"
p.Size = Vector3.new(%f, %f, %f)
p.Position = Vector3.new(%f, %f, %f)
p.Color = Color3.fromRGB(%d, %d, %d)
p.Material = Enum.Material.%s
p.Anchored = %s
p.CanCollide = %s
p.Parent = workspace
]],
        part.ClassName,
        part.Name,
        part.Size.X, part.Size.Y, part.Size.Z,
        part.Position.X, part.Position.Y, part.Position.Z,
        math.floor(part.Color.R * 255), math.floor(part.Color.G * 255), math.floor(part.Color.B * 255),
        part.Material.Name,
        tostring(part.Anchored),
        tostring(part.CanCollide)
    )
    return code
end

local fullCode = "-- Generated by Serializer\n"
for _, obj in ipairs(TargetFolder:GetDescendants()) do
    if obj:IsA("BasePart") then
        fullCode = fullCode .. serializePart(obj)
    end
end

-- สั่งคัดลอกข้อความทั้งหมดลง Clipboard ในเครื่องคุณ
if setclipboard then
    setclipboard(fullCode)
    print("คัดลอกโค้ดวัตถุลง Clipboard เรียบร้อยแล้ว!")
else
    print("Executor ไม่รองรับ setclipboard ให้เปิด F9 คัดลอกโค้ดเอง")
end
